### ISSUE TITLE
request: glibc 2.28 support for AlmaLinux 8.7 users

### ISSUE THREAD

**Issue by Lovinity** [sapphiredev/type#429]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

The prebuilt binaries released do not include ones for glibc 2.28, which is used in AlmaLinux 8.7 (CentOS replacement). Therefore, Sapphire cannot run on an AlmaLinux 8.7 system without manually building it (which is very tedious considering this package is often a dependency and used within a package manager, which fails because it could not find a prebuilt for glibc 2.28 to download).

### Desired solution

Prebuilt binaries for glibc 2.28 in releases.

### Alternatives considered

Building manually; very tedious and not worth the amount of effort necessary, especially for every new release.

Using a different version of glibc; also very tedious when AlmaLinux is basically set to use 2.28 by default. Even AlmaLinux 9 uses 2.34, which is also not included in prebuilt binaries.

**Comment by Lovinity** [comment]
Actually, upon further testing, this is only an npm issue; yarn will automatically fall back to building.

**Comment by vladfrangu** [comment]
Could you share the npm logs you get when building?

**Comment by favna** [comment]
I thought I replied to this. Weird. Anyway, we don't have the liberty of choosing specific glibc versions easily, as we are limited by docker images runnable by GitHub workflows, with some leeway because can provide a custom image. If you can set up a workflow job for this stack and PR it then sure we'll add it, but because I'm personally not familiar with how glibc really works (my knowledge goes to "install and it works") nor do I know AlmaLinux I'm not really the best person to add it.

**Comment by Lovinity** [comment]
Sorry for the delay in replying. Docker limitations makes sense. I switched to yarn and haven't had any issues. I will need to get back with you on the NPM error log later once I have a free moment.

**Comment by favna** [comment]
Closing this as not planned as per my comment above
